[package]
name = "radishmemory-source-vault"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
aead-stream.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
keyring-core.workspace = true
sha2.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
radishmemory-windows-filesystem.workspace = true
windows-native-keyring-store.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store.workspace = true
security-framework.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
secret-service.workspace = true
zbus-secret-service-keyring-store.workspace = true
