[package]
name = "radishmemory-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
fixture-runner = []

[dependencies]
radishmemory-core.workspace = true
rusqlite.workspace = true

[dev-dependencies]
radishmemory-file-entry = { workspace = true, features = ["acceptance-test-support"] }
