[package]
name = "radishmemory-windows-filesystem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true

[lints.rust]
unsafe_code = "deny"
unused_crate_dependencies = "deny"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
